# You have to set PAT and add secrete ACCESS_OKREGISTRY in the repo {{{PKG}}}
# see also the default template: https://github.com/JuliaCI/PkgTemplates.jl/blob/master/templates/github/workflows/register.yml
# Also see [Running GitHub Actions Sequentially](https://stevenmortimer.com/running-github-actions-sequentially/) to separate updateokreg out from CI.yml, and trigger TagBot sequentially.
# CHECKPOINT: Currently substitution (e.g., {{{PKG}}}) failed.

name: Register Package to OkRegistry
on:
  push:
    paths:
      - 'Project.toml'
  issue_comment:
    types:
      - created
  workflow_dispatch:


permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
# `contents: write` is required to allow `peter-evans/repository-dispatch`. You may alternatively on your github go to [settings-actions](https://github.com/okatsn/{{{PKG}}}.jl/settings/actions) to set the default permissions granted to the `GITHUB_TOKEN` to Read and write.
jobs:
  UpdateOkReg:
    # if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-20.04
    steps:
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.6.7
      - uses: actions/checkout@v3 # see https://github.com/actions/checkout
        with:
          path: TEMP
      - uses: actions/checkout@v3 # see https://github.com/actions/checkout
        with:
          repository: okatsn/OkRegistry
          path: OkRegistry
          token: ${{ secrets.ACCESS_OKREGISTRY }}
    # actions/checkout clones repo
      - run: |
          cd OkRegistry
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          julia --project=@. -e '
            using Pkg;
            Pkg.instantiate();
            Pkg.Registry.add(RegistrySpec(url = "https://github.com/okatsn/OkRegistry.git"));
            include("add_local_pkg_to_registry.jl");
            '
    # Update OkRegistry first.
    # 1. Current path is critical. Please refer to "add_local_pkg_to_registry.jl" in OkRegistry.
    # 2. `git config` is required, and has to be done in repo OkRegistry (cd OkRegistry must precede)
    # 3. Personal registry is add per julia install; that is, OkRegistry should be added before `Pkg.instantiate()`
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2 # See https://github.com/peter-evans/repository-dispatch
        with:
          repository: ${{ github.repository }}
          event-type: trigger-tagbot
          token: ${{ secrets.GITHUB_TOKEN }} # default is GITHUB_TOKEN

##  `with` Options for `name: Trigger next workflow`:
### - `client-payload:` passes data from Workflow 1 to Workflow 2
###   - Example: 
#       ```
#       with:
#         client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
#       ```
#     - Commit message can be obtained from both 
#       - `${{ github.event.commits[0].message }}` and 
#       - `${{ github.event.head_commit.message }}`
#       - (Not sure) the latter one could be empty
#       - (Not sure) error with the latter one could result from permission: content: false
#       - It is possible to [Iterating over github.event.commits](https://github.com/orgs/community/discussions/35120) or [use join function to concatenate commits](https://github.com/orgs/community/discussions/25164).
#       - Alternative way to [Get a commit](https://docs.github.com/en/rest/git/commits?apiVersion=2022-11-28#get-a-commit) using `curl`.
#     - 1
#     - 1
#     - 1
#     - 1
#     - 1
#     - 1
#     - 1
#     - 1



# client-payload: '{"ref": "${{ github.ref }}", "custom": "${{ github.event.commits[0].message }}"}'
# client-payload: '{"ref": "${{ github.ref }}", "custom": "${{ github.event.commits[0].message }}"}'
# client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}' # `client-payload:` passes data from Workflow 1 to Workflow 2
# token: ${{ secrets.REPO_GHA_PAT }} #default is GITHUB_TOKEN
# Noted that commit message can be obtained from both ${{ github.event.commits[0].message }} and ${{ github.event.head_commit.message }}, but the latter one could be empty.