name: TestPkgDev
on:
  push:
    paths:
      - 'VersionTemp.toml'
      - '.github/workflows/PkgDev.yml'
  workflow_dispatch:


permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  TestPkgDev:
    runs-on: ubuntu-20.04
    steps: 
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.6.7
      - run: |
          git init
          git config user.email "action@github.com"
          git config user.name "github-actions"
          julia --project=@. -e '
            using Pkg;
            Pkg.Registry.add([Pkg.RegistrySpec(name = "General", uuid = "23338594-aafe-5451-b93e-139f81909106", url = "https://github.com/JuliaRegistries/General.git"), Pkg.RegistrySpec(name = "OkRegistry", uuid = "86e7831a-6f1f-4f41-b710-281fd69cacb1", url = "https://github.com/okatsn/OkRegistry.git")]);
            Pkg.instantiate();
            Pkg.develop("TestTagBot");
            Pkg.add("PkgDev");
            using PkgDev;
            PkgDev.tag("TestTagBot", v"0.2.11"; github_username="github-actions", release_notes="Hello World");
            '

# CHECKPOINT: (INCOMPLETE)
# - This action is intended to automate the process of version-up, compatibility check process proceeding the register (register.yml), tagging (TagBot.yml).
# - It failed at:
#     ERROR: Did not find credentials for github.com in the git credential manager.
#     Stacktrace:
#     [1] error(s::String)
#       @ Base ./error.jl:33
#     [2] tag_internal(package_name::String, pkg_uuid::Base.UUID, pkg_path::String, version::VersionNumber; registry::Nothing, release_notes::String, credentials::Nothing, github_username::String)
#       @ PkgDev ~/.julia/packages/PkgDev/3Nmfz/src/tag.jl:124
#     [3] tag(package_name::String, version::VersionNumber; kwargs::Base.Iterators.Pairs{Symbol, String, Tuple{Symbol, Symbol}, NamedTuple{(:github_username, :release_notes), Tuple{String, String}}})
#       @ PkgDev ~/.julia/packages/PkgDev/3Nmfz/src/tag.jl:18
#     [4] top-level scope
#       @ none:8
#   At the `LibGit2.GitCredential(GitConfig(), "https://github.com")` line in tag.jl